2020-10-06 16:15:49 {Progress} [INFO] Se enviará el siguiente archivo: 02-06-2020-12.30.03.pdf, con tamaño: 5.844194412231445 MB
2020-10-06 16:15:49 {Connection} [INFO] Escuchando desde 0.0.0.0:9898
2020-10-06 16:15:49 {Connection} [INFO] Se espera la conexión de un usuario para empezar la transmisión
2020-10-06 16:15:49 {Connection} [INFO] Máximo número de clientes aceptados: 1
2020-10-06 16:15:58 {Connection} [INFO] El usuario ('127.0.0.1', 52383) se ha conectado 1/1
2020-10-06 16:15:58 {TCP_Packets} [INFO] Enviando INFO al Cliente: 02-06-2020-12.30.03.pdf<SEPARATOR>6128082<SEPARATOR>6a5315bfbe68f7f8f01f22ce0e9daa3e60a071c92dc2948e28c4a545841a2066
2020-10-06 16:15:58 {Connection} [ERROR] local variable 'bytes_read' referenced before assignment
Traceback (most recent call last):
  File "D:/University/2020-2/Infraestructura de comunicaciones/S2G6_laboratorio3-1/src/server/server.py", line 104, in threaded
    while bytes_read:
UnboundLocalError: local variable 'bytes_read' referenced before assignment
